behavior:
  auto_send_recording: false
bot:
  gender: female
  image: /static/bots_profile/renée.png
  name: Renée
  voice: Ali
language:
  learning: fr
  level: intermediate
  native: fr
model:
  name: gpt-3.5-turbo
  temperature: 0.3
user:
  gender: Female
  image: ''
  name: ''
