behavior:
  auto_send_recording: true
bot:
  gender: female
  image: /static/bots_profile/marie.png
  name: Marie
  voice: Ali
language:
  learning: fr
  level: intermediate
  native: fr
model:
  name: gpt-3.5-turbo
  temperature: 0.8
user:
  gender: Female
  image: ''
  name: ''
